---
  # ref: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
  - name: Install docker & k3s
    hosts: all
    become: true
    become_user: scott
    vars:
      current_user: "{{ lookup('env', 'USER') }}"
    tasks:
     - name: update apt
       apt:
         upgrade: yes
         update_cache: yes
         cache_valid_time: 86400 #One day
